//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IshtiaqComsats.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person1
    {
        public int personId { get; set; }
        public string Name { get; set; }
        public string Contact { get; set; }
        public string Adress { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> ReligionId { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual Religion Religion { get; set; }
    }
}
